version: '3.8'

services:
  api:
    build:
      context: ./api            # Path to API service
    ports:
      - "8000:8000"              # Expose API on port 8000

  streamlit:
    build:
      context: ./streamlit       # Path to Streamlit service
    ports:
      - "8501:8501"              # Expose Streamlit on port 8501

  frontend:
    build:
      context: ./frontend        # Path to frontend service
    ports:
      - "3000:3000"              # Expose frontend on port 3000
